import { Column, Product } from './types';

export const COLUMNS: Column[] = [
  { key: 'code', label: 'CÓD.', width: 'w-24' },
  { key: 'name', label: 'PRODUCTO', width: 'w-64' },
  { key: 'unit', label: 'UNIDAD', width: 'w-32' },
  { key: 'calvia', label: 'CALVIA', width: 'w-28' },
  { key: 'palmanova', label: 'PALMANOVA', width: 'w-28' },
  { key: 'magaluf', label: 'MAGALUF', width: 'w-28' },
  { key: 'ocell', label: 'SON FERRER', width: 'w-28' },
  { key: 'santaPonsa', label: 'SANTA PONSA', width: 'w-28' },
  { key: 'bendinat', label: 'BENDINAT', width: 'w-28' },
  { key: 'picarol', label: 'PAGUERA', width: 'w-28' },
  { key: 'vedellet', label: 'EL TORO', width: 'w-28' },
  { key: 'molinet', label: 'GALATZO', width: 'w-28' },
  { key: 'naBurguesa', label: 'SON CALIU', width: 'w-28' },
];

export const INITIAL_DATA: Product[] = [
  { code: '1409', name: 'FRESAS', unit: 'Kg', locations: {} },
  { code: '3512', name: 'KIWIS', unit: 'Kg', locations: { calvia: '3', palmanova: '4', ocell: '3', bendinat: '4', picarol: '2', naBurguesa: '5' } },
  { code: '3542', name: 'LIMÓN', unit: 'Kg', locations: { palmanova: '1', magaluf: '1' } },
  { code: '5686', name: 'MANZANA GOLDEN', unit: 'Kg', locations: { palmanova: '6', magaluf: '15', ocell: '5', picarol: '2', vedellet: '3', molinet: '4', naBurguesa: '14' } },
  { code: '2571', name: 'MELOCOTÓN', unit: 'Kg', locations: {} },
  { code: '3578', name: 'MELÓN', unit: 'Kg', locations: { calvia: '2', palmanova: '6', santaPonsa: '3' } },
  { code: '3604', name: 'NARANJA NAVEL', unit: 'Kg', locations: { calvia: '8', palmanova: '6', magaluf: '10', ocell: '5', picarol: '3', vedellet: '5', molinet: '3', naBurguesa: '5' } },
  { code: '3683', name: 'CLEMENTINA', unit: 'Kg', locations: { calvia: '5', palmanova: '6', magaluf: '10', ocell: '8', santaPonsa: '6', bendinat: '4', picarol: '3', vedellet: '5', molinet: '5', naBurguesa: '8' } },
  { code: '3591', name: 'NECTARINA', unit: 'Kg', locations: {} },
  { code: '6001', name: 'PERAS BLANQUILLA', unit: 'Kg', locations: { ocell: '12' } },
  { code: '6400', name: 'PERA CONFERENCIA', unit: 'Kg', locations: { calvia: '8', palmanova: '8', magaluf: '15', santaPonsa: '8', bendinat: '6', picarol: '3', vedellet: '6', molinet: '4', naBurguesa: '14' } },
  { code: '1706', name: 'PLATANOS PRIMERA', unit: 'UNIDAD', locations: { calvia: '60', palmanova: '100', magaluf: '120', ocell: '100', santaPonsa: '100', bendinat: '100', picarol: '100', vedellet: '80', molinet: '100', naBurguesa: '110' } },
  { code: '4790', name: 'SANDIA', unit: 'Kg', locations: {} },
  { code: '10', name: 'ACELGAS', unit: 'Manojo', locations: { calvia: '2', magaluf: '4', ocell: '2', santaPonsa: '2', bendinat: '1', picarol: '1' } },
  { code: '3041', name: 'AJO BLANCO', unit: 'Kg', locations: { palmanova: '1', magaluf: '1', santaPonsa: '1', bendinat: '1' } },
  { code: '3080', name: 'APIO', unit: 'Manojo', locations: { santaPonsa: '1', bendinat: '1', picarol: '1', molinet: '1' } },
  { code: '4123', name: 'BERENJENA', unit: 'Kg', locations: {} },
  { code: '4142', name: 'BONIATO ROJO', unit: 'Kg', locations: {} },
  { code: '458', name: 'BROCOLI', unit: 'Kg', locations: {} },
  { code: '4180', name: 'CALABACINES VERDES', unit: 'Kg', locations: { calvia: '8', palmanova: '4', magaluf: '8', ocell: '4', santaPonsa: '1', bendinat: '4', picarol: '2', molinet: '4' } },
  { code: '1160', name: 'CALABAZA', unit: 'Kg', locations: { calvia: '4', palmanova: '1', magaluf: '6', ocell: '2', santaPonsa: '1' } },
  { code: '230', name: 'CEBOLLAS', unit: 'Kg', locations: { calvia: '2', palmanova: '3', magaluf: '6', ocell: '1', santaPonsa: '3', bendinat: '3', picarol: '2', vedellet: '3' } },
  { code: '1244', name: 'CHAMPIÑONES', unit: 'Bandeja', locations: { palmanova: '3', magaluf: '4', bendinat: '2' } },
  { code: '300', name: 'COL', unit: 'UNIDAD', locations: {} },
  { code: '380', name: 'ESPINACAS', unit: 'Manojo', locations: { calvia: '1', palmanova: '1', magaluf: '1', ocell: '2', santaPonsa: '1', bendinat: '1', picarol: '1', vedellet: '2' } },
  { code: '500', name: 'LAUREL', unit: 'Manojo', locations: { magaluf: '1', santaPonsa: '1', picarol: '1' } },
  { code: '3521', name: 'LECHUGA Iceberg', unit: 'Unidad', locations: { calvia: '1', palmanova: '2', magaluf: '3', ocell: '2', santaPonsa: '1', bendinat: '2', vedellet: '1', molinet: '2' } },
  { code: '518', name: 'NABOS', unit: 'Kg', locations: {} },
  { code: '692', name: 'PATATAS', unit: 'Bolsa 5 KG', multiplier: 5, locations: { calvia: '4', santaPonsa: '1', bendinat: '3', picarol: '1', molinet: '1' } },
  { code: '691', name: 'PATATAS', unit: 'Bolsa 25 Kg', multiplier: 25, locations: { magaluf: '2', ocell: '1', picarol: '1', vedellet: '1' } },
  { code: '9660', name: 'PEPINOS', unit: 'Kg', locations: {} },
  { code: '670', name: 'PEREJIL', unit: 'Manojo', locations: { palmanova: '1', magaluf: '1', ocell: '1', santaPonsa: '1', picarol: '1' } },
  { code: '4720', name: 'PIMIENTO ROJO', unit: 'Kg', locations: { calvia: '1', palmanova: '2', magaluf: '2', ocell: '2', santaPonsa: '2', bendinat: '2', picarol: '1', vedellet: '1', molinet: '2' } },
  { code: '4725', name: 'PIMIENTO VERDE Italiano', unit: 'Kg', locations: { calvia: '0,5', palmanova: '2', magaluf: '2', ocell: '2', santaPonsa: '1', bendinat: '1', picarol: '1', vedellet: '1' } },
  { code: '782', name: 'PUERROS', unit: 'Manojo', locations: { calvia: '4', magaluf: '10', ocell: '8', santaPonsa: '8', bendinat: '7', picarol: '5', vedellet: '6', molinet: '2' } },
  { code: '9905', name: 'TOMATES Daniela ensalada', unit: 'Kg', locations: { calvia: '6', palmanova: '3', magaluf: '4', ocell: '6', santaPonsa: '4', bendinat: '5', picarol: '2', vedellet: '3' } },
  { code: '9907', name: 'TOMATES Daniela', unit: 'Kg', locations: { palmanova: '3', magaluf: '6', ocell: '4', bendinat: '5', picarol: '2', vedellet: '2', molinet: '4', naBurguesa: '2' } },
  { code: '1980', name: 'ZANAHORIAS', unit: 'Bolsa 5 Kg', multiplier: 5, locations: { calvia: '1', magaluf: '2', ocell: '2', santaPonsa: '1', bendinat: '1', vedellet: '1' } },
  { code: '3471', name: 'HINOJO', unit: 'Manojo', locations: { calvia: '1' } },
  { code: '801', name: 'CEBOLLETA', unit: 'Manojo', locations: { magaluf: '2', santaPonsa: '3', vedellet: '1' } },
  { code: '360', name: 'COLIFLOR', unit: 'Unidad', locations: { santaPonsa: '1' } },
];
